<?php

namespace MC\PlatformBundle\Repository;

/**
 * ReponsesCandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponsesCandidatRepository extends \Doctrine\ORM\EntityRepository
{
}
